/**
 * @file index_page.h
 * @brief Main (Home) page HTML
 * 
 * Uses common styles from common_styles.h
 */

#ifndef INDEX_PAGE_H
#define INDEX_PAGE_H

#include "common_styles.h"

static const char INDEX_HTML[] = 
HTML_HEAD_START
"    <title>Acoustic Monitor</title>\n"
HTML_STYLE_START
COMMON_STYLES
HTML_STYLE_END
HTML_HEAD_END
"<body>\n"
HTML_GLOBAL_STATUS_BAR
"    <div class=\"container\">\n"
"        <header class=\"header\">\n"
"            <a href=\"/\" class=\"header-link\" title=\"Refresh\" onclick=\"location.reload(); return false;\">🏠</a>\n"
"            <h1>Acoustic Monitor</h1>\n"
"            <a href=\"/ml\" class=\"header-link\" title=\"ML Configuration\">⚙️</a>\n"
"        </header>\n"
"        <div class=\"info-bar\">\n"
"            <div class=\"storage-info\" id=\"storage-text\">Loading...</div>\n"
"            <div class=\"storage-bar\"><div class=\"storage-fill\" id=\"storage-fill\"></div></div>\n"
"        </div>\n"
"        <div class=\"controls-panel\">\n"
"            <div class=\"controls-row-main\" id=\"controls\">\n"
"                <button class=\"btn btn-monitor ctrl-btn\" onclick=\"startContinuous('continuous')\" id=\"btn-cont\">\n"
"                    <span class=\"status-indicator\" id=\"status-cont\"></span>🔄 Monitor\n"
"                </button>\n"
"                <button class=\"btn btn-danger ctrl-btn\" onclick=\"stopMonitor()\" id=\"btn-stop\">⏹ Stop</button>\n"
"            </div>\n"
"            <div class=\"controls-row-secondary\">\n"
"                <button class=\"btn btn-teal ctrl-btn\" onclick=\"runSingle()\" id=\"btn-single\">▶ Single</button>\n"
"                <button class=\"btn btn-teal ctrl-btn\" onclick=\"quickRecord()\" id=\"btn-quick\">🔴 Record 16s</button>\n"
"                <button class=\"btn btn-yellow ctrl-btn\" onclick=\"runCalibration()\" id=\"btn-calib\">🎯 Calibrate</button>\n"
"            </div>\n"
"            <!-- Waterfall button hidden -->\n"
"            <button class=\"btn btn-orange ctrl-btn\" onclick=\"startContinuous('waterfall')\" id=\"btn-wf\" style=\"display:none;\">\n"
"                <span class=\"status-indicator\" id=\"status-wf\"></span>📊 Waterfall\n"
"            </button>\n"
"            <div class=\"progress-wrap\" id=\"progress-wrap\">\n"
"                <div class=\"progress-track\"><div class=\"progress-fill\" id=\"progress-fill\"></div></div>\n"
"                <div class=\"progress-label\" id=\"progress-label\"></div>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"files-panel\">\n"
"            <div class=\"file-list\" id=\"file-list\">\n"
"                <div class=\"loading\">Loading files...</div>\n"
"            </div>\n"
"            <div class=\"upload-area\" id=\"upload-area\" onclick=\"document.getElementById('file-input').click()\">\n"
"                <input type=\"file\" id=\"file-input\" onchange=\"uploadFile()\">\n"
"                <span class=\"upload-content\" id=\"upload-content\">\n"
"                    <span style=\"font-size:20px; margin-right:8px;\">📤</span>\n"
"                    <span>Click or drag file</span>\n"
"                </span>\n"
"                <span class=\"upload-progress\" id=\"upload-progress\" style=\"display:none;\">\n"
"                    <span style=\"font-size:20px; margin-right:8px;\">⏳</span>\n"
"                    <span id=\"upload-status\">Uploading...</span>\n"
"                </span>\n"
"            </div>\n"
"        </div>\n"
"        <div class=\"system-block\">\n"
"            <button class=\"btn btn-system btn-restart\" onclick=\"restartDevice()\">🔄 Reboot device</button>\n"
"            <button class=\"btn btn-system btn-format\" onclick=\"formatFs()\">🗑 Format</button>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        function formatSize(bytes) {\n"
"            if (bytes < 1024) return bytes + ' B';\n"
"            if (bytes < 1024*1024) return (bytes/1024).toFixed(1) + ' KB';\n"
"            return (bytes/1024/1024).toFixed(2) + ' MB';\n"
"        }\n"
"        async function loadFiles() {\n"
"            try {\n"
"                const res = await fetch('/api/files');\n"
"                const data = await res.json();\n"
"                const list = document.getElementById('file-list');\n"
"                const storageText = document.getElementById('storage-text');\n"
"                const storageFill = document.getElementById('storage-fill');\n"
"                \n"
"                freeBytes = data.free;\n"
"                const usedPct = ((data.total - data.free) / data.total * 100).toFixed(1);\n"
"                storageText.textContent = `${formatSize(data.free)} free / ${formatSize(data.total)} total`;\n"
"                storageFill.style.width = usedPct + '%';\n"
"                \n"
"                if (!data.files || data.files.length === 0) {\n"
"                    list.innerHTML = '<div class=\"empty-msg\">No files</div>';\n"
"                    return;\n"
"                }\n"
"                list.innerHTML = data.files.map(f => {\n"
"                    const isAudio = f.name.endsWith('.wav') || f.name.endsWith('.WAV');\n"
"                    const safeId = f.name.replace(/[^a-zA-Z0-9]/g, '_');\n"
"                    return `\n"
"                    <div class=\"file-item\">\n"
"                        <div class=\"file-row\">\n"
"                            <span class=\"file-icon\">${f.is_dir ? '📁' : (isAudio ? '🎵' : '📄')}</span>\n"
"                            <span class=\"file-name\" title=\"${f.name}\">${f.name}</span>\n"
"                            <span class=\"file-size\">${formatSize(f.size)}</span>\n"
"                            <div class=\"file-actions\">\n"
"                                ${isAudio ? `<button class=\"btn btn-small btn-play\" id=\"play-${safeId}\" onclick=\"playAudio('${f.name}', '${safeId}')\">▶️</button>` : ''}\n"
"                                ${!f.is_dir ? `<button class=\"btn btn-small\" onclick=\"copyUrl('${f.name}')\">📋</button>` : ''}\n"
"                                ${!f.is_dir ? `<a class=\"btn\" href=\"/api/file?path=/${encodeURIComponent(f.name)}\" download>⬇<span class=\"btn-text\"> Download</span></a>` : ''}\n"
"                                <button class=\"btn btn-danger\" onclick=\"deleteFile('${f.name}')\">🗑<span class=\"btn-text\"></span></button>\n"
"                            </div>\n"
"                        </div>\n"
"                        ${isAudio ? `<div class=\"audio-progress\" id=\"progress-${safeId}\"><div class=\"audio-progress-fill\" id=\"progress-fill-${safeId}\"></div></div>` : ''}\n"
"                    </div>\n"
"                `}).join('');\n"
"            } catch (e) {\n"
"                document.getElementById('file-list').innerHTML = '<div class=\"empty-msg\">Error loading files</div>';\n"
"            }\n"
"        }\n"
"        async function deleteFile(name) {\n"
"            if (!confirm(`Delete ${name}?`)) return;\n"
"            try {\n"
"                await fetch(`/api/file?path=/${encodeURIComponent(name)}`, { method: 'DELETE' });\n"
"                loadFiles();\n"
"            } catch (e) { alert('Delete failed'); }\n"
"        }\n"
"        function copyUrl(name) {\n"
"            const url = location.origin + '/api/file?path=/' + encodeURIComponent(name);\n"
"            const ta = document.createElement('textarea');\n"
"            ta.value = url;\n"
"            ta.style.position = 'fixed';\n"
"            ta.style.opacity = '0';\n"
"            document.body.appendChild(ta);\n"
"            ta.select();\n"
"            try {\n"
"                document.execCommand('copy');\n"
"                alert('📋 URL copied!');\n"
"            } catch (e) {\n"
"                prompt('Copy URL:', url);\n"
"            }\n"
"            document.body.removeChild(ta);\n"
"        }\n"
"        let currentAudio = null;\n"
"        let currentPlayBtn = null;\n"
"        let currentProgressBar = null;\n"
"        let currentProgressFill = null;\n"
"        function playAudio(name, safeId) {\n"
"            const btn = document.getElementById('play-' + safeId);\n"
"            const progressBar = document.getElementById('progress-' + safeId);\n"
"            const progressFill = document.getElementById('progress-fill-' + safeId);\n"
"            if (currentAudio && currentPlayBtn === btn) {\n"
"                currentAudio.pause();\n"
"                currentAudio = null;\n"
"                btn.textContent = '▶️';\n"
"                btn.classList.remove('playing');\n"
"                if (currentProgressBar) currentProgressBar.classList.remove('active');\n"
"                currentPlayBtn = null;\n"
"                currentProgressBar = null;\n"
"                return;\n"
"            }\n"
"            if (currentAudio) {\n"
"                currentAudio.pause();\n"
"                if (currentPlayBtn) {\n"
"                    currentPlayBtn.textContent = '▶️';\n"
"                    currentPlayBtn.classList.remove('playing');\n"
"                }\n"
"                if (currentProgressBar) currentProgressBar.classList.remove('active');\n"
"            }\n"
"            const url = '/api/file?path=/' + encodeURIComponent(name);\n"
"            currentAudio = new Audio(url);\n"
"            currentPlayBtn = btn;\n"
"            currentProgressBar = progressBar;\n"
"            currentProgressFill = progressFill;\n"
"            btn.textContent = '⏹️';\n"
"            btn.classList.add('playing');\n"
"            progressBar.classList.add('active');\n"
"            progressFill.style.width = '0%';\n"
"            currentAudio.play();\n"
"            currentAudio.ontimeupdate = () => {\n"
"                if (currentAudio.duration > 0) {\n"
"                    const pct = (currentAudio.currentTime / currentAudio.duration) * 100;\n"
"                    progressFill.style.width = pct + '%';\n"
"                }\n"
"            };\n"
"            currentAudio.onended = () => {\n"
"                btn.textContent = '▶️';\n"
"                btn.classList.remove('playing');\n"
"                progressBar.classList.remove('active');\n"
"                currentAudio = null;\n"
"                currentPlayBtn = null;\n"
"                currentProgressBar = null;\n"
"            };\n"
"            currentAudio.onerror = () => {\n"
"                btn.textContent = '▶️';\n"
"                btn.classList.remove('playing');\n"
"                progressBar.classList.remove('active');\n"
"                alert('Cannot play audio');\n"
"                currentAudio = null;\n"
"                currentPlayBtn = null;\n"
"                currentProgressBar = null;\n"
"            };\n"
"        }\n"
"        let progressTimer = null;\n"
"        function showProgress(type, label, durationMs) {\n"
"            const wrap = document.getElementById('progress-wrap');\n"
"            const fill = document.getElementById('progress-fill');\n"
"            const lbl = document.getElementById('progress-label');\n"
"            wrap.classList.add('active');\n"
"            fill.className = 'progress-fill ' + type;\n"
"            fill.style.width = '0%';\n"
"            lbl.textContent = label;\n"
"            if (progressTimer) clearInterval(progressTimer);\n"
"            let elapsed = 0;\n"
"            const step = 100;\n"
"            progressTimer = setInterval(() => {\n"
"                elapsed += step;\n"
"                const pct = Math.min(100, (elapsed / durationMs) * 100);\n"
"                fill.style.width = pct + '%';\n"
"                if (elapsed >= durationMs) clearInterval(progressTimer);\n"
"            }, step);\n"
"        }\n"
"        function hideProgress() {\n"
"            if (progressTimer) { clearInterval(progressTimer); progressTimer = null; }\n"
"            const wrap = document.getElementById('progress-wrap');\n"
"            wrap.classList.remove('active');\n"
"            const fill = document.getElementById('progress-fill');\n"
"            fill.style.width = '0%';\n"
"            fill.style.animation = '';\n"
"        }\n"
"        function setCtrlBtns(disabled, exceptStop) {\n"
"            document.querySelectorAll('.ctrl-btn').forEach(b => b.disabled = disabled);\n"
"            document.getElementById('btn-stop').disabled = exceptStop ? false : disabled;\n"
"        }\n"
"        function enableAllBtns() {\n"
"            document.querySelectorAll('.ctrl-btn').forEach(b => b.disabled = false);\n"
"            document.getElementById('btn-stop').disabled = false;\n"
"            hideProgress();\n"
"        }\n"
"        async function quickRecord() {\n"
"            setCtrlBtns(true, false);\n"
"            const btn = document.getElementById('btn-quick');\n"
"            btn.textContent = '🔴 Rec...';\n"
"            showProgress('rec', '🔴 Recording... (16s)', 16000);\n"
"            try {\n"
"                await fetch('/api/monitor/record?duration=16', { method: 'POST' });\n"
"                setTimeout(() => {\n"
"                    btn.textContent = '💾 Saving...';\n"
"                    showProgressIndeterminate('💾 Saving to disk...');\n"
"                    const pollUntilIdle = async () => {\n"
"                        const res = await fetch('/api/monitor/status');\n"
"                        const data = await res.json();\n"
"                        if (data.idle) {\n"
"                            hideProgress();\n"
"                            loadFiles();\n"
"                            enableAllBtns();\n"
"                            btn.textContent = '🔴 Record 16s';\n"
"                            if (data.error) alert('Error: ' + data.error);\n"
"                        } else {\n"
"                            setTimeout(pollUntilIdle, 500);\n"
"                        }\n"
"                    };\n"
"                    pollUntilIdle();\n"
"                }, 16000);\n"
"            } catch (e) { hideProgress(); enableAllBtns(); btn.textContent = '🔴 Record 16s'; }\n"
"        }\n"
"        async function startContinuous(mode) {\n"
"            setCtrlBtns(true, true);\n"
"            try {\n"
"                await fetch('/api/monitor/' + mode, { method: 'POST' });\n"
"                updateMonitorStatus();\n"
"            } catch (e) { enableAllBtns(); }\n"
"        }\n"
"        async function runSingle() {\n"
"            setCtrlBtns(true, false);\n"
"            const btn = document.getElementById('btn-single');\n"
"            btn.textContent = '⏳ Running...';\n"
"            try {\n"
"                await fetch('/api/monitor/single', { method: 'POST' });\n"
"                setTimeout(() => { enableAllBtns(); btn.textContent = '▶ Single'; }, 3000);\n"
"            } catch (e) { enableAllBtns(); btn.textContent = '▶ Single'; }\n"
"        }\n"
"        async function runCalibration() {\n"
"            if (!confirm('🎯 Start calibration?\\n\\nPhase 1: Recording (~16 sec)\\nPhase 2: Processing\\n\\nDevice should be in normal operation mode.')) return;\n"
"            setCtrlBtns(true, false);\n"
"            const btn = document.getElementById('btn-calib');\n"
"            btn.textContent = '🔴 Recording...';\n"
"            showProgress('rec', '🔴 Recording... (16s)', 16000);\n"
"            const fetchPromise = fetch('/api/calibrate', { method: 'POST' })\n"
"                .then(r => r.json())\n"
"                .catch(e => ({ status: 'error', error: e.message }));\n"
"            setTimeout(() => {\n"
"                btn.textContent = '⏳ Processing...';\n"
"                showProgressIndeterminate('🔄 Processing embeddings...');\n"
"            }, 16000);\n"
"            const result = await fetchPromise;\n"
"            hideProgress();\n"
"            enableAllBtns();\n"
"            btn.textContent = '🎯 Calibrate';\n"
"            if (result.status === 'ok') {\n"
"                alert('✅ Calibration complete!');\n"
"            } else {\n"
"                alert('❌ Error: ' + (result.error || 'Unknown error'));\n"
"            }\n"
"        }\n"
"        function showProgressIndeterminate(label) {\n"
"            const wrap = document.getElementById('progress-wrap');\n"
"            const fill = document.getElementById('progress-fill');\n"
"            const lbl = document.getElementById('progress-label');\n"
"            wrap.classList.add('active');\n"
"            fill.className = 'progress-fill processing';\n"
"            fill.style.width = '100%';\n"
"            fill.style.animation = 'pulse 1s ease-in-out infinite';\n"
"            lbl.textContent = label;\n"
"            if (progressTimer) { clearInterval(progressTimer); progressTimer = null; }\n"
"        }\n"
"        async function stopMonitor() {\n"
"            try {\n"
"                await fetch('/api/monitor/stop', { method: 'POST' });\n"
"                // Hide status bar immediately and block re-showing for 2 seconds\n"
"                stopRequestedAt = Date.now();\n"
"                anomalyHideTime = 0;\n"
"                const bar = document.getElementById('global-status-bar');\n"
"                if (bar) { bar.className = 'global-status-bar'; }\n"
"                document.body.classList.remove('has-status-bar');\n"
"                setTimeout(() => { enableAllBtns(); updateMonitorStatus(); }, 500);\n"
"            } catch (e) { enableAllBtns(); }\n"
"        }\n"
"        async function updateMonitorStatus() {\n"
"            try {\n"
"                const res = await fetch('/api/monitor/status');\n"
"                const data = await res.json();\n"
"                const isCont = data.continuous;\n"
"                const isCalib = data.calibrating;\n"
"                document.getElementById('status-cont').className = 'status-indicator' + (isCont ? ' active' : '');\n"
"                document.getElementById('status-wf').className = 'status-indicator' + (isCont ? ' active' : '');\n"
"                if (isCont) { setCtrlBtns(true, true); }\n"
"                // Show calibration progress if started from button\n"
"                const btn = document.getElementById('btn-calib');\n"
"                if (isCalib && data.calibration) {\n"
"                    setCtrlBtns(true, false);\n"
"                    const c = data.calibration;\n"
"                    if (c.state === 'recording') {\n"
"                        btn.textContent = '🔴 Recording...';\n"
"                        if (!progressTimer) showProgress('rec', '🔴 Recording... (16s)', 16000);\n"
"                    } else if (c.state === 'processing') {\n"
"                        btn.textContent = '⏳ Processing...';\n"
"                        showProgressIndeterminate('🔄 Processing embeddings...');\n"
"                    } else if (c.state === 'saving') {\n"
"                        btn.textContent = '💾 Saving...';\n"
"                        showProgressIndeterminate('💾 Saving calibration...');\n"
"                    }\n"
"                } else if (!isCont && btn.textContent !== '🎯 Calibrate') {\n"
"                    btn.textContent = '🎯 Calibrate';\n"
"                    hideProgress();\n"
"                    enableAllBtns();\n"
"                }\n"
"            } catch (e) { }\n"
"        }\n"
"        setInterval(updateMonitorStatus, 1000);\n"
"        async function restartDevice() {\n"
"            if (!confirm('🔄 Reboot device?\\n\\nThe device will restart and reconnect to WiFi.')) return;\n"
"            try {\n"
"                await fetch('/api/system/restart', { method: 'POST' });\n"
"                showRebootOverlay();\n"
"            } catch (e) { }\n"
"        }\n"
"        function showRebootOverlay() {\n"
"            const overlay = document.createElement('div');\n"
"            overlay.id = 'reboot-overlay';\n"
"            overlay.innerHTML = `\n"
"                <div style=\"position:fixed; top:0; left:0; right:0; bottom:0; background:rgba(0,0,0,0.85); z-index:9999; display:flex; flex-direction:column; justify-content:center; align-items:center;\">\n"
"                    <div style=\"font-size:48px; margin-bottom:20px;\">🔄</div>\n"
"                    <div style=\"font-size:20px; color:#fff; margin-bottom:30px;\">Rebooting device...</div>\n"
"                    <div style=\"width:80%; max-width:400px; height:8px; background:#333; border-radius:4px; overflow:hidden;\">\n"
"                        <div id=\"reboot-progress\" style=\"height:100%; width:0%; background:linear-gradient(90deg, #0f9, #0cf); transition:width 0.1s linear;\"></div>\n"
"                    </div>\n"
"                    <div style=\"margin-top:15px; color:#888; font-size:14px;\" id=\"reboot-status\">Restarting...</div>\n"
"                </div>\n"
"            `;\n"
"            document.body.appendChild(overlay);\n"
"            let progress = 0;\n"
"            const interval = setInterval(() => {\n"
"                progress += 2;\n"
"                document.getElementById('reboot-progress').style.width = progress + '%';\n"
"                if (progress >= 60) document.getElementById('reboot-status').textContent = 'Reconnecting...';\n"
"                if (progress >= 100) {\n"
"                    clearInterval(interval);\n"
"                    document.getElementById('reboot-status').textContent = 'Reloading page...';\n"
"                    setTimeout(() => location.reload(), 500);\n"
"                }\n"
"            }, 100);\n"
"        }\n"
"        async function formatFs() {\n"
"            const code = Math.floor(100 + Math.random() * 900);\n"
"            const input = prompt(`⚠️ WARNING! All files will be deleted!\\n\\nEnter code to confirm: ${code}`);\n"
"            if (input === null) return;\n"
"            if (input !== String(code)) { alert('❌ Invalid code'); return; }\n"
"            try {\n"
"                const res = await fetch('/api/fs/format', { method: 'POST' });\n"
"                if (res.ok) { alert('✅ Format complete'); loadFiles(); }\n"
"                else alert('❌ Format failed');\n"
"            } catch (e) { alert('❌ Error: ' + e); }\n"
"        }\n"
"        let freeBytes = 0;\n"
"        async function uploadFile() {\n"
"            const input = document.getElementById('file-input');\n"
"            if (!input.files.length) { alert('Select a file first'); return; }\n"
"            const file = input.files[0];\n"
"            if (freeBytes > 0 && file.size > freeBytes) {\n"
"                alert(`❌ File too large!\\n\\nFile size: ${(file.size/1024).toFixed(1)} KB\\nFree space: ${(freeBytes/1024).toFixed(1)} KB`);\n"
"                return;\n"
"            }\n"
"            const uploadContent = document.getElementById('upload-content');\n"
"            const uploadProgress = document.getElementById('upload-progress');\n"
"            const uploadStatus = document.getElementById('upload-status');\n"
"            uploadContent.style.display = 'none';\n"
"            uploadProgress.style.display = 'inline';\n"
"            uploadStatus.textContent = '0%';\n"
"            try {\n"
"                const xhr = new XMLHttpRequest();\n"
"                xhr.upload.onprogress = (e) => {\n"
"                    if (e.lengthComputable) {\n"
"                        uploadStatus.textContent = (e.loaded/e.total*100).toFixed(0) + '%';\n"
"                    }\n"
"                };\n"
"                xhr.onload = () => {\n"
"                    uploadContent.style.display = 'inline';\n"
"                    uploadProgress.style.display = 'none';\n"
"                    if (xhr.status === 200) { input.value=''; loadFiles(); }\n"
"                    else alert('Upload failed: ' + xhr.statusText);\n"
"                };\n"
"                xhr.onerror = () => {\n"
"                    uploadContent.style.display = 'inline';\n"
"                    uploadProgress.style.display = 'none';\n"
"                    alert('Upload error');\n"
"                };\n"
"                xhr.open('POST', '/api/upload?filename=' + encodeURIComponent(file.name));\n"
"                xhr.send(file);\n"
"            } catch (e) {\n"
"                uploadContent.style.display = 'inline';\n"
"                uploadProgress.style.display = 'none';\n"
"                alert('Upload failed');\n"
"            }\n"
"        }\n"
"        function setupDragAndDrop() {\n"
"            const area = document.getElementById('upload-area');\n"
"            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\n"
"                document.body.addEventListener(eventName, e => { e.preventDefault(); e.stopPropagation(); }, false);\n"
"            });\n"
"            ['dragenter', 'dragover'].forEach(eventName => {\n"
"                area.addEventListener(eventName, () => area.classList.add('drag-over'), false);\n"
"            });\n"
"            ['dragleave', 'drop'].forEach(eventName => {\n"
"                area.addEventListener(eventName, () => area.classList.remove('drag-over'), false);\n"
"            });\n"
"            area.addEventListener('drop', e => {\n"
"                const files = e.dataTransfer.files;\n"
"                if (files.length > 0) {\n"
"                    document.getElementById('file-input').files = files;\n"
"                    uploadFile();\n"
"                }\n"
"            }, false);\n"
"        }\n"
"        setupDragAndDrop();\n"
"        loadFiles();\n"
"\n"
"        // Global status monitoring\n"
JS_GLOBAL_STATUS
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // INDEX_PAGE_H
