/**
 * @file ml_config_page.h
 * @brief ML Configuration page HTML
 * 
 * Uses common styles from common_styles.h
 */

#ifndef ML_CONFIG_PAGE_H
#define ML_CONFIG_PAGE_H

#include "common_styles.h"

static const char ML_CONFIG_HTML[] = 
HTML_HEAD_START
"    <title>ML Configuration</title>\n"
HTML_STYLE_START
COMMON_STYLES
HTML_STYLE_END
HTML_HEAD_END
"<body>\n"
HTML_GLOBAL_STATUS_BAR
"    <div class=\"container-wide\">\n"
"        <header class=\"header\">\n"
"            <a href=\"/\" class=\"header-link\" title=\"Home\">🏠</a>\n"
"            <h1>ML Configuration</h1>\n"
"            <a href=\"/ml\" class=\"header-link disabled\" title=\"ML Configuration (current)\">⚙️</a>\n"
"        </header>\n"
"\n"
"        <!-- Models -->\n"
"        <div class=\"panel\">\n"
"            <h2>📦 Models</h2>\n"
"            <ul class=\"model-list\" id=\"model-list\">\n"
"                <li class=\"empty-msg\">Loading models...</li>\n"
"            </ul>\n"
"            <div class=\"upload-area\" id=\"upload-area\" onclick=\"document.getElementById('model-upload').click()\">\n"
"                <input type=\"file\" id=\"model-upload\" accept=\".tflite\" onchange=\"uploadModel(this)\">\n"
"                <span id=\"upload-content\">\n"
"                    <span style=\"font-size:24px; margin-right:10px;\">📤</span>\n"
"                    <span>Click or drag model (.tflite)</span>\n"
"                </span>\n"
"                <span id=\"upload-progress\" style=\"display:none;\">\n"
"                    <span style=\"font-size:24px; margin-right:10px;\">⏳</span>\n"
"                    <span id=\"upload-status\">0%</span>\n"
"                </span>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <!-- Calibrations -->\n"
"        <div class=\"panel\">\n"
"            <h2>📊 Calibrations</h2>\n"
"            <div style=\"margin-bottom:15px;\">\n"
"                <label>Select model: </label>\n"
"                <select id=\"calib-model-select\" onchange=\"loadCalibrations()\">\n"
"                    <option value=\"\">-- Select Model --</option>\n"
"                </select>\n"
"            </div>\n"
"            <ul class=\"calib-list\" id=\"calib-list\">\n"
"                <li class=\"empty-msg\">Select a model to view calibrations</li>\n"
"            </ul>\n"
"        </div>\n"
"\n"
"        <!-- Anomaly Detector -->\n"
"        <div class=\"panel\">\n"
"            <h2>🎯 Anomaly Detector</h2>\n"
"            <p style=\"color:var(--text-muted); margin-bottom:15px;\">Configure anomaly detection settings. Changes are applied immediately. Click 'Save' to persist to NVS.</p>\n"
"            <div style=\"display:flex; flex-wrap:wrap; gap:15px; margin-bottom:15px;\">\n"
"                <div style=\"flex:1; min-width:200px;\">\n"
"                    <label style=\"display:block; margin-bottom:5px; color:var(--text-muted);\">Algorithm:</label>\n"
"                    <select id=\"detector-algorithm\" onchange=\"changeDetectorSettings()\" style=\"width:100%;\">\n"
"                        <option value=\"\">Loading...</option>\n"
"                    </select>\n"
"                </div>\n"
"                <div style=\"flex:1; min-width:200px;\">\n"
"                    <label style=\"display:block; margin-bottom:5px; color:var(--text-muted);\">Threshold Method:</label>\n"
"                    <select id=\"detector-threshold-method\" onchange=\"onThresholdMethodChange()\" style=\"width:100%;\">\n"
"                        <option value=\"\">Loading...</option>\n"
"                    </select>\n"
"                </div>\n"
"                <div style=\"flex:1; min-width:150px;\">\n"
"                    <label style=\"display:block; margin-bottom:5px; color:var(--text-muted);\">Value:</label>\n"
"                    <input type=\"number\" id=\"detector-threshold-value\" step=\"0.1\" min=\"0.1\" max=\"100\" style=\"width:100%;\">\n"
"                </div>\n"
"            </div>\n"
"            <div style=\"display:flex; gap:10px; margin-bottom:15px;\">\n"
"                <button class=\"btn\" onclick=\"changeDetectorSettings()\">Apply</button>\n"
"                <button class=\"btn btn-orange\" onclick=\"saveDetectorSettings()\">💾 Save to NVS</button>\n"
"            </div>\n"
"            <div class=\"status-box\">\n"
"                <span class=\"label\">Status:</span> <span id=\"detector-calibrated\">Loading...</span>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <!-- Embedded Model Calibration -->\n"
"        <div class=\"panel\">\n"
"            <h2>🔧 Embedded Model Calibration</h2>\n"
"            <p style=\"color:var(--text-muted); margin-bottom:15px;\">Calibration data stored in dedicated flash partition for the built-in model.</p>\n"
"            <div id=\"embedded-calib-status\" style=\"margin-bottom:15px;\">Loading...</div>\n"
"            <button class=\"btn btn-danger\" id=\"btn-delete-embedded\" onclick=\"deleteEmbeddedCalib()\" style=\"display:none;\">🗑 Delete Embedded Calibration</button>\n"
"        </div>\n"
"\n"
"        <!-- Storage Info -->\n"
"        <div class=\"panel\">\n"
"            <h2>💾 ML Storage</h2>\n"
"            <div id=\"mlfs-info\">Loading...</div>\n"
"            <button class=\"btn btn-danger\" onclick=\"formatMLFS()\" style=\"margin-top:15px;\">🗑 Format ML Storage</button>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        let models = [];\n"
"        let detectorAlgorithms = [];\n"
"        let detectorThresholdMethods = [];\n"
"\n"
"        async function loadDetectorSettings() {\n"
"            try {\n"
"                const res = await fetch('/api/ml/detector');\n"
"                const data = await res.json();\n"
"                detectorAlgorithms = data.algorithms || [];\n"
"                detectorThresholdMethods = (data.threshold && data.threshold.methods) || [];\n"
"                \n"
"                const algSelect = document.getElementById('detector-algorithm');\n"
"                algSelect.innerHTML = detectorAlgorithms.map(a => \n"
"                    `<option value=\"${a.id}\" ${!a.available ? 'disabled' : ''} ${a.id === data.current ? 'selected' : ''}>${a.name}${!a.available ? ' (N/A)' : ''}</option>`\n"
"                ).join('');\n"
"                \n"
"                const thrMethodSelect = document.getElementById('detector-threshold-method');\n"
"                thrMethodSelect.innerHTML = detectorThresholdMethods.map(m => \n"
"                    `<option value=\"${m.id}\" data-default=\"${m.default}\" ${m.id === data.threshold.method ? 'selected' : ''}>${m.name}</option>`\n"
"                ).join('');\n"
"                \n"
"                document.getElementById('detector-threshold-value').value = data.threshold.value.toFixed(1);\n"
"                \n"
"                document.getElementById('detector-calibrated').innerHTML = data.calibrated ? \n"
"                    '<span style=\"color:var(--accent-primary);\">✅ Calibrated</span>' : \n"
"                    '<span style=\"color:var(--accent-warning);\">⚠️ Not calibrated (always returns OK)</span>';\n"
"            } catch (e) {\n"
"                document.getElementById('detector-calibrated').textContent = '❌ Error loading';\n"
"            }\n"
"        }\n"
"\n"
"        function onThresholdMethodChange() {\n"
"            const select = document.getElementById('detector-threshold-method');\n"
"            const option = select.options[select.selectedIndex];\n"
"            if (option && option.dataset.default) {\n"
"                document.getElementById('detector-threshold-value').value = parseFloat(option.dataset.default).toFixed(1);\n"
"            }\n"
"        }\n"
"\n"
"        async function changeDetectorSettings() {\n"
"            const algId = parseInt(document.getElementById('detector-algorithm').value);\n"
"            const thrMethod = parseInt(document.getElementById('detector-threshold-method').value);\n"
"            const thrValue = parseFloat(document.getElementById('detector-threshold-value').value);\n"
"            \n"
"            if (isNaN(algId) || isNaN(thrMethod) || isNaN(thrValue)) return;\n"
"            \n"
"            document.getElementById('detector-calibrated').innerHTML = '<span style=\"color:var(--accent-yellow);\">⏳ Applying...</span>';\n"
"            \n"
"            try {\n"
"                const res = await fetch('/api/ml/detector', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({algorithm: algId, threshold_method: thrMethod, threshold_value: thrValue})\n"
"                });\n"
"                if (res.ok) {\n"
"                    loadDetectorSettings();\n"
"                } else {\n"
"                    alert('❌ Failed to apply settings');\n"
"                    loadDetectorSettings();\n"
"                }\n"
"            } catch (e) {\n"
"                alert('❌ Error: ' + e.message);\n"
"                loadDetectorSettings();\n"
"            }\n"
"        }\n"
"\n"
"        async function saveDetectorSettings() {\n"
"            const algId = parseInt(document.getElementById('detector-algorithm').value);\n"
"            const thrMethod = parseInt(document.getElementById('detector-threshold-method').value);\n"
"            const thrValue = parseFloat(document.getElementById('detector-threshold-value').value);\n"
"            \n"
"            if (isNaN(algId) || isNaN(thrMethod) || isNaN(thrValue)) return;\n"
"            \n"
"            document.getElementById('detector-calibrated').innerHTML = '<span style=\"color:var(--accent-yellow);\">⏳ Saving...</span>';\n"
"            \n"
"            try {\n"
"                const res = await fetch('/api/ml/detector', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({algorithm: algId, threshold_method: thrMethod, threshold_value: thrValue, save: true})\n"
"                });\n"
"                const data = await res.json();\n"
"                if (res.ok && data.saved) {\n"
"                    alert('✅ Settings saved to NVS');\n"
"                    loadDetectorSettings();\n"
"                } else {\n"
"                    alert('❌ Failed to save settings');\n"
"                    loadDetectorSettings();\n"
"                }\n"
"            } catch (e) {\n"
"                alert('❌ Error: ' + e.message);\n"
"                loadDetectorSettings();\n"
"            }\n"
"        }\n"
"\n"
"        async function loadModels() {\n"
"            try {\n"
"                const res = await fetch('/api/ml/models');\n"
"                const data = await res.json();\n"
"                models = data.models || [];\n"
"                const list = document.getElementById('model-list');\n"
"                if (models.length === 0) {\n"
"                    list.innerHTML = '<li class=\"empty-msg\">No models uploaded</li>';\n"
"                    return;\n"
"                }\n"
"                list.innerHTML = models.map(m => `\n"
"                    <li class=\"model-item\">\n"
"                        <div class=\"model-info\">\n"
"                            <div class=\"model-name\">📦 ${m.name}${m.is_active ? '<span class=\"badge badge-active\">ACTIVE</span>' : ''}</div>\n"
"                            <div class=\"model-size\">${(m.size / 1024).toFixed(1)} KB</div>\n"
"                        </div>\n"
"                        <div>\n"
"                            ${!m.is_active ? `<button class=\"btn btn-small\" onclick=\"activateModel('${m.name}')\">Activate</button>` : ''}\n"
"                            <button class=\"btn btn-small btn-danger\" onclick=\"deleteModel('${m.name}')\">Delete</button>\n"
"                        </div>\n"
"                    </li>\n"
"                `).join('');\n"
"                updateModelSelect();\n"
"            } catch (e) {\n"
"                document.getElementById('model-list').innerHTML = '<li class=\"empty-msg\">❌ Failed to load models</li>';\n"
"            }\n"
"        }\n"
"\n"
"        function updateModelSelect() {\n"
"            const select = document.getElementById('calib-model-select');\n"
"            const activeModelName = models.find(m => m.is_active)?.name || '';\n"
"            select.innerHTML = '<option value=\"\">-- Select Model --</option>' +\n"
"                models.map(m => `<option value=\"${m.name}\" ${m.is_active ? 'selected' : ''}>${m.name}</option>`).join('');\n"
"            if (activeModelName) {\n"
"                select.value = activeModelName;\n"
"                loadCalibrations();\n"
"            }\n"
"        }\n"
"\n"
"        async function loadCalibrations() {\n"
"            const model = document.getElementById('calib-model-select').value;\n"
"            const list = document.getElementById('calib-list');\n"
"            if (!model) {\n"
"                list.innerHTML = '<li class=\"empty-msg\">Select a model to view calibrations</li>';\n"
"                return;\n"
"            }\n"
"            try {\n"
"                const res = await fetch(`/api/ml/calibrations?model=${encodeURIComponent(model)}`);\n"
"                const data = await res.json();\n"
"                const calibs = data.calibrations || [];\n"
"                if (calibs.length === 0) {\n"
"                    list.innerHTML = '<li class=\"empty-msg\">No calibrations for this model<br><button class=\"btn\" style=\"margin-top:15px;\" onclick=\"runCalibration(\\'' + model + '\\')\">🎯 Run Calibration</button></li>';\n"
"                    return;\n"
"                }\n"
"                list.innerHTML = calibs.map(c => `\n"
"                    <li class=\"calib-item\">\n"
"                        <div class=\"calib-info\">\n"
"                            <div class=\"calib-name\">📊 ${c.name}${c.is_active ? '<span class=\"badge badge-active\">ACTIVE</span>' : ''}</div>\n"
"                            <div class=\"calib-meta\">Threshold: ${c.threshold?.toFixed(3) || 'N/A'} | Samples: ${c.samples || 'N/A'}</div>\n"
"                        </div>\n"
"                        <div>\n"
"                            ${!c.is_active ? `<button class=\"btn btn-small\" onclick=\"activateCalib('${model}', '${c.name}')\">Activate</button>` : ''}\n"
"                            <button class=\"btn btn-small btn-danger\" onclick=\"deleteCalib('${model}', '${c.name}')\">Delete</button>\n"
"                        </div>\n"
"                    </li>\n"
"                `).join('') + '<li><button class=\"btn\" style=\"margin-top:10px;\" onclick=\"runCalibration(\\'' + model + '\\')\">🎯 Run New Calibration</button></li>';\n"
"            } catch (e) {\n"
"                list.innerHTML = '<li class=\"empty-msg\">❌ Failed to load calibrations</li>';\n"
"            }\n"
"        }\n"
"\n"
"        async function loadMLFSInfo() {\n"
"            try {\n"
"                const res = await fetch('/api/ml/fs/info');\n"
"                const data = await res.json();\n"
"                const pct = ((data.used / data.total) * 100).toFixed(1);\n"
"                document.getElementById('mlfs-info').innerHTML = `\n"
"                    <div style=\"margin-bottom:10px;\">\n"
"                        <strong>Total:</strong> ${(data.total / 1024).toFixed(1)} KB | \n"
"                        <strong>Used:</strong> ${(data.used / 1024).toFixed(1)} KB (${pct}%) | \n"
"                        <strong>Free:</strong> ${(data.free / 1024).toFixed(1)} KB\n"
"                    </div>\n"
"                    <div class=\"storage-bar\" style=\"height:20px;\">\n"
"                        <div class=\"storage-fill\" style=\"width:${pct}%;\"></div>\n"
"                    </div>\n"
"                `;\n"
"            } catch (e) {\n"
"                document.getElementById('mlfs-info').textContent = '❌ Failed to load storage info';\n"
"            }\n"
"        }\n"
"\n"
"        function uploadModel(input) {\n"
"            const file = input.files[0];\n"
"            if (!file) return;\n"
"            \n"
"            if (!file.name.endsWith('.tflite')) {\n"
"                alert('❌ Please select a .tflite file');\n"
"                input.value = '';\n"
"                return;\n"
"            }\n"
"            \n"
"            const uploadContent = document.getElementById('upload-content');\n"
"            const uploadProgress = document.getElementById('upload-progress');\n"
"            const uploadStatus = document.getElementById('upload-status');\n"
"            \n"
"            uploadContent.style.display = 'none';\n"
"            uploadProgress.style.display = 'inline';\n"
"            uploadStatus.textContent = '0%';\n"
"            \n"
"            const xhr = new XMLHttpRequest();\n"
"            xhr.upload.onprogress = (e) => {\n"
"                if (e.lengthComputable) {\n"
"                    uploadStatus.textContent = (e.loaded/e.total*100).toFixed(0) + '%';\n"
"                }\n"
"            };\n"
"            xhr.onload = () => {\n"
"                uploadContent.style.display = 'inline';\n"
"                uploadProgress.style.display = 'none';\n"
"                input.value = '';\n"
"                \n"
"                if (xhr.status === 200) {\n"
"                    loadModels();\n"
"                    loadMLFSInfo();\n"
"                } else {\n"
"                    alert('❌ Upload failed: ' + xhr.statusText);\n"
"                }\n"
"            };\n"
"            xhr.onerror = () => {\n"
"                uploadContent.style.display = 'inline';\n"
"                uploadProgress.style.display = 'none';\n"
"                input.value = '';\n"
"                alert('❌ Upload error');\n"
"            };\n"
"            xhr.open('POST', '/api/ml/models/upload?filename=' + encodeURIComponent(file.name));\n"
"            xhr.setRequestHeader('Content-Type', 'application/octet-stream');\n"
"            xhr.send(file);\n"
"        }\n"
"\n"
"        async function activateModel(name) {\n"
"            if (!confirm(`Activate model: ${name}?\\n\\nThis will:\\n- Load model from flash to PSRAM\\n- Reinitialize inference engine\\n- Take ~1-2 seconds`)) return;\n"
"            \n"
"            document.querySelectorAll('.btn').forEach(b => b.disabled = true);\n"
"            \n"
"            try {\n"
"                const res = await fetch('/api/ml/models/activate', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({model: name})\n"
"                });\n"
"                \n"
"                if (res.ok) {\n"
"                    const data = await res.json();\n"
"                    alert(`✅ Model activated!\\n\\nModel: ${data.model}`);\n"
"                    loadModels();\n"
"                    loadDetectorSettings();\n"
"                } else {\n"
"                    const errorText = await res.text();\n"
"                    alert('❌ Activation failed: ' + errorText);\n"
"                }\n"
"            } catch (e) {\n"
"                alert('❌ Error: ' + e.message);\n"
"            } finally {\n"
"                document.querySelectorAll('.btn').forEach(b => b.disabled = false);\n"
"            }\n"
"        }\n"
"\n"
"        async function deleteModel(name) {\n"
"            if (!confirm(`⚠️ Delete model: ${name}?\\n\\nThis action cannot be undone.`)) return;\n"
"            \n"
"            try {\n"
"                const res = await fetch('/api/ml/models/' + encodeURIComponent(name), { method: 'DELETE' });\n"
"                if (res.ok) {\n"
"                    alert(`✅ Model deleted: ${name}`);\n"
"                    loadModels();\n"
"                    loadMLFSInfo();\n"
"                } else {\n"
"                    const errorText = await res.text();\n"
"                    alert('❌ Delete failed: ' + errorText);\n"
"                }\n"
"            } catch (e) {\n"
"                alert('❌ Error: ' + e.message);\n"
"            }\n"
"        }\n"
"\n"
"        async function activateCalib(model, name) {\n"
"            if (!confirm(`Activate calibration: ${name}?`)) return;\n"
"            try {\n"
"                const res = await fetch('/api/ml/calibrations/activate', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({model: model, calibration: name})\n"
"                });\n"
"                if (res.ok) {\n"
"                    alert('✅ Calibration activated!');\n"
"                    loadCalibrations();\n"
"                    loadDetectorSettings();\n"
"                } else {\n"
"                    const errorText = await res.text();\n"
"                    alert('❌ Activation failed: ' + errorText);\n"
"                }\n"
"            } catch (e) { alert('❌ Error: ' + e.message); }\n"
"        }\n"
"\n"
"        async function deleteCalib(model, name) {\n"
"            if (!confirm(`⚠️ Delete calibration: ${name}?\\n\\nThis action cannot be undone.`)) return;\n"
"            try {\n"
"                const res = await fetch(`/api/ml/calibrations/delete?model=${encodeURIComponent(model)}&name=${encodeURIComponent(name)}`, { method: 'DELETE' });\n"
"                if (res.ok) {\n"
"                    alert('✅ Calibration deleted');\n"
"                    loadCalibrations();\n"
"                    loadMLFSInfo();\n"
"                } else {\n"
"                    const errorText = await res.text();\n"
"                    alert('❌ Delete failed: ' + errorText);\n"
"                }\n"
"            } catch (e) { alert('❌ Error: ' + e.message); }\n"
"        }\n"
"\n"
"        async function runCalibration(model) {\n"
"            if (!confirm(`🎯 Run calibration for model: ${model}?\\n\\nThe device will:\\n1. Record audio samples\\n2. Process and calculate threshold\\n3. Save calibration file`)) return;\n"
"            \n"
"            const list = document.getElementById('calib-list');\n"
"            list.innerHTML = '<li class=\"empty-msg\">🔄 Running calibration... Please wait (~15 seconds)</li>';\n"
"            \n"
"            try {\n"
"                const res = await fetch('/api/calibrate', { method: 'POST' });\n"
"                const data = await res.json();\n"
"                if (res.ok && data.status === 'ok') {\n"
"                    alert(`✅ Calibration complete!\\nThreshold: ${data.threshold?.toFixed(4) || 'N/A'}`);\n"
"                    loadCalibrations();\n"
"                } else {\n"
"                    alert('❌ Calibration failed: ' + (data.error || 'Unknown error'));\n"
"                    loadCalibrations();\n"
"                }\n"
"            } catch (e) {\n"
"                alert('❌ Error: ' + e);\n"
"                loadCalibrations();\n"
"            }\n"
"        }\n"
"\n"
"        async function formatMLFS() {\n"
"            const code = Math.floor(100 + Math.random() * 900);\n"
"            const input = prompt(`⚠️ WARNING! All models and calibrations will be deleted!\\n\\nEnter code to confirm: ${code}`);\n"
"            if (input === null) return;\n"
"            if (input !== String(code)) { alert('❌ Invalid code'); return; }\n"
"            try {\n"
"                const res = await fetch('/api/ml/fs/format', { method: 'POST' });\n"
"                if (res.ok) { alert('✅ ML storage formatted'); location.reload(); }\n"
"                else alert('❌ Format failed');\n"
"            } catch (e) { alert('❌ Error: ' + e); }\n"
"        }\n"
"\n"
"        async function loadEmbeddedCalibStatus() {\n"
"            try {\n"
"                const res = await fetch('/api/ml/embedded_calib');\n"
"                const data = await res.json();\n"
"                const statusEl = document.getElementById('embedded-calib-status');\n"
"                const btnEl = document.getElementById('btn-delete-embedded');\n"
"                if (data.exists) {\n"
"                    statusEl.innerHTML = '<span style=\"color:var(--accent-primary);\">✅ Calibration exists</span>';\n"
"                    btnEl.style.display = 'inline-block';\n"
"                } else {\n"
"                    statusEl.innerHTML = '<span style=\"color:var(--text-muted);\">❌ No calibration (detector disabled)</span>';\n"
"                    btnEl.style.display = 'none';\n"
"                }\n"
"            } catch (e) {\n"
"                document.getElementById('embedded-calib-status').textContent = '❌ Error loading status';\n"
"            }\n"
"        }\n"
"\n"
"        async function deleteEmbeddedCalib() {\n"
"            if (!confirm('⚠️ Delete embedded model calibration?\\n\\nThe detector will be disabled until you recalibrate.')) return;\n"
"            try {\n"
"                const res = await fetch('/api/ml/embedded_calib', { method: 'DELETE' });\n"
"                if (res.ok) {\n"
"                    alert('✅ Embedded calibration deleted');\n"
"                    loadEmbeddedCalibStatus();\n"
"                    loadDetectorSettings();\n"
"                } else {\n"
"                    const errorText = await res.text();\n"
"                    alert('❌ Delete failed: ' + errorText);\n"
"                }\n"
"            } catch (e) { alert('❌ Error: ' + e.message); }\n"
"        }\n"
"\n"
"        function setupDragAndDrop() {\n"
"            const area = document.getElementById('upload-area');\n"
"            \n"
"            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\n"
"                document.body.addEventListener(eventName, e => { e.preventDefault(); e.stopPropagation(); }, false);\n"
"            });\n"
"            \n"
"            ['dragenter', 'dragover'].forEach(eventName => {\n"
"                area.addEventListener(eventName, () => area.classList.add('drag-over'), false);\n"
"            });\n"
"            \n"
"            ['dragleave', 'drop'].forEach(eventName => {\n"
"                area.addEventListener(eventName, () => area.classList.remove('drag-over'), false);\n"
"            });\n"
"            \n"
"            area.addEventListener('drop', e => {\n"
"                const files = e.dataTransfer.files;\n"
"                if (files.length > 0) {\n"
"                    const input = document.getElementById('model-upload');\n"
"                    input.files = files;\n"
"                    uploadModel(input);\n"
"                }\n"
"            }, false);\n"
"        }\n"
"\n"
"        window.onload = () => {\n"
"            loadModels();\n"
"            loadMLFSInfo();\n"
"            loadDetectorSettings();\n"
"            loadEmbeddedCalibStatus();\n"
"            setupDragAndDrop();\n"
"        };\n"
"\n"
"        // Global status monitoring\n"
JS_GLOBAL_STATUS
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // ML_CONFIG_PAGE_H
