idf_component_register(SRCS "main.c"
                            "chip_info.c"
                            "led_control.c"
                            "button_handler.c"
                            "i2s_handler.c"
                            "flash_storage.c"
                            "fs_manager.c"
                            "mlfs_manager.c"
                            "wifi_manager.c"
                            "web_server.c"
                            "recorder.c"
                            "monitor.c"
                            "mel_spectrogram.c"
                            "audio_process.c"
                            "test.c"
                            "inference.cc"
                            "anomaly_detector.c"
                            "calibration.c"
                            "model_manager.c"
                            "calib_manager.c"
                            "embedded_calib.c"
                    PRIV_REQUIRES esp_driver_i2s esp_driver_gpio esp_timer esp_partition partition_table spi_flash nvs_flash esp_wifi esp_netif esp_event esp_http_server json
                    REQUIRES esp_psram
                    INCLUDE_DIRS "." "ml")
